---
- hosts: cluster_ip
  become: true
  tasks:


###### 

  - name: Initialize the Kubernetes cluster using kubeadm
    #command: kubeadm init --apiserver-advertise-address="54.254.159.139" --apiserver-cert-extra-sans="10.50.0.200" --node-name k8s-master --pod-network-cidr=10.55.0.0/16
    command: kubeadm init --control-plane-endpoint="{{ IP_LB }}" --upload-certs --apiserver-advertise-address=0.0.0.0 --pod-network-cidr=192.168.0.0/16


  - name: Pause for 1 minutes to build apiserver k8s
    pause:
      minutes: 1
## ubuntu user to access the Kubernetes cluster
#  - name: Setup kubeconfig for ubuntu user
#    command: "{{ item }}"
#    with_items:
#     - mkdir -p /home/{{ user_deploy }}/.kube
#     - rsync -av /etc/kubernetes/admin.conf /home/{{ user_deploy }}/.kube/config
#     - chown -R {{ user_deploy }}:{{ user_deploy }} /home/{{ user_deploy }}/.kube

## container networking provider
  - name: Install calico pod network
    become: true
    command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml



## Generate kube master join command
  - name: Create a new certificate key
    become: true
    command: kubeadm init phase upload-certs --upload-certs
    register: join_certificate_key

  - name: Generate master join command
    become: true
    command: kubeadm token create --print-join-command --certificate-key "{{ join_certificate_key.stdout_lines[2] }}"
    register: join_master_command

  - name: Copy master join command to local file
    become: false
    local_action: copy content="{{ join_master_command.stdout_lines[0] }}" dest="./k8s_koin_master"

## Generate kube join command
  - name: Generate join command
    become: true
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

## start docker 
  handlers:
    - name: docker status
      service: name=docker state=started